- name: PlayBook 1
  hosts: Nginx-Servers
  become: true
  tasks:
    - name: Installing Nginx web server
      apt:
        name: nginx
        state: latest
    - name: start nginx and enable nginx service
      service:
        name: nginx
        state: started
        enabled: yes  # if you want to also enable nginx



- name: PlayBook 2
  become: yes
  hosts: Database-Servers
  tasks:
    - name: Installing Mysql and dependencies
      package:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - mysql-server
        - mysql-client
        - python3-mysqldb
        - libmysqlclient-dev

    - name: Fail if MySQL installation failed
      fail:
        msg: "MySQL installation failed, check the previous task logs."
      when: "'mysql-server' not in ansible_facts.packages"

    - name: Start and enable mysql service
      service:
        name: mysql
        state: started
        enabled: yes
      when: ansible_facts.services.mysql is defined

    - name: Creating mysql user 
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_pass }}"
        priv: '*.*:ALL'
        host: '%'
        state: present   

    - name: Creating realcloud_db
      mysql_db:
        name: "{{ db_name }}"
        state: present    

    - name: Enable remote login to mysql
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
        backup: yes
      when: ansible_facts['os_family'] == "Debian"


- name: PlayBook 3
  hosts: Apache-Servers
  become: true
  tasks:  
      - name: Install Apache Webserver
        apt: 
          name: apache2
          update_cache: yes 
          state: latest
      - name: Enable Apache on system reboot
        service: 
          name: apache2
          enabled: yes

      - name: Create document root for domain configured in host variable
        file:
          path: "/var/www/{{ http_host }}"
          state: directory
          owner: www-data
          group: www-data
          mode: '0755'
 
      - name: Copy your index file
        template:
           src: "files/index-template.html"
           dest: "/var/www/{{ http_host }}/index.html"
 
      - name: Set up virtuahHost
        template:
           src: "files/apache-template.conf"
           dest: "/etc/apache2/sites-available/{{ http_conf }}"
 
      - name: Enable site
        command: a2ensite {{ http_conf }}
 
      - name: "UFW firewall allow HTTP on port {{ http_port }}"
        ufw:
          rule: allow
          port: "{{ http_port }}"
          proto: tcp
        notify:
          - Restart Apache
          - Restart Mysql

  handlers:
    - name: Restart Apache
      service: 
        name: apache2 
        state: restarted
    - name: Restart Mysql
      service:
        name: mysql
        state: restarted
    
